[font]
size = 8
normal.family = "0xProto Nerd Font"

[keyboard]
bindings = [
{ key = "Return", mods = "Control | Shift", action = "SpawnNewInstance" },
]

[general]
import = [
    "~/.config/alacritty/themes/catppuccin_mocha.toml"
]
